# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# https://docs.travis-ci.com/user/database-setup/#PostgreSQL
services:
  - postgresql

before_script:
  - psql -c 'create database medicizer' -U postgres
  - psql -c 'create user "medicizer"; grant all privileges on database medicizer to "medicizer"' -U postgres

addons:
  postgresql: "10"
# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
  - master
  - travis
  - frontdev
  - backdev

#https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables
env:

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
#notifications:
#  email: false

script: mvn clean verify